# Generated by Django 5.1.15 on 2026-04-23 03:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Иконка Font Awesome')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Процент бонусов')),
                ('bonus_to_rub_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Курс бонуса к рублю')),
                ('welcome_bonus', models.IntegerField(default=500, verbose_name='Приветственный бонус')),
                ('referral_bonus', models.IntegerField(default=200, verbose_name='Реферальный бонус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Настройки бонусной системы',
                'verbose_name_plural': 'Настройки бонусной системы',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='bonus_used',
            field=models.IntegerField(default=0, verbose_name='Списано бонусов'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='design_preference',
            field=models.TextField(blank=True, verbose_name='Ссылка на желаемый дизайн'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_prepaid',
            field=models.BooleanField(default=False, verbose_name='Предоплата внесена'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма предоплаты'),
        ),
        migrations.AddField(
            model_name='client',
            name='bonus_balance',
            field=models.IntegerField(default=0, verbose_name='Бонусный баланс'),
        ),
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='main.client'),
        ),
        migrations.AddField(
            model_name='master',
            name='certificates',
            field=models.TextField(blank=True, verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='master',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='master',
            name='social_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization',
            field=models.CharField(choices=[('manicure', 'Маникюр'), ('pedicure', 'Педикюр'), ('design', 'Дизайн'), ('all', 'Все направления')], default='all', max_length=20, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='master',
            name='work_experience',
            field=models.CharField(blank=True, max_length=150, verbose_name='Опыт работы (текст)'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='color_scheme',
            field=models.CharField(choices=[('pink', 'Розовый'), ('red', 'Красный'), ('white', 'Белый'), ('black', 'Черный'), ('blue', 'Синий'), ('green', 'Зеленый'), ('purple', 'Фиолетовый'), ('multicolor', 'Многоцветный')], default='multicolor', max_length=20, verbose_name='Цветовая схема'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='design_type',
            field=models.CharField(choices=[('french', 'Френч'), ('gradient', 'Градиент'), ('glitter', 'Блестки'), ('stones', 'Стразы'), ('molding', 'Лепка'), ('stamping', 'Стемпинг'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип дизайна'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AddField(
            model_name='service',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярная услуга'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('category', models.CharField(choices=[('care', 'Уход'), ('design', 'Дизайны'), ('tips', 'Советы'), ('news', 'Новости')], max_length=20, verbose_name='Категория')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='main.master')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.blogpost')),
            ],
            options={
                'verbose_name': 'Комментарий к статье',
                'verbose_name_plural': 'Комментарии к статьям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('type', models.CharField(choices=[('accrual', 'Начисление'), ('spending', 'Списание')], max_length=20, verbose_name='Тип')),
                ('source', models.CharField(choices=[('appointment', 'Запись'), ('review', 'Отзыв'), ('referral', 'Реферал'), ('welcome', 'Приветственный бонус')], max_length=20, verbose_name='Источник')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бонусная транзакция',
                'verbose_name_plural': 'Бонусные транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='main.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер сертификата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Номинал')),
                ('buyer_name', models.CharField(max_length=150, verbose_name='Имя покупателя')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Email покупателя')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Имя получателя')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('message', models.TextField(blank=True, verbose_name='Поздравительное сообщение')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Активирован')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата активации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='PDF файл')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Подарочный сертификат',
                'verbose_name_plural': 'Подарочные сертификаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('prepaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предоплата')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID платежа')),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('bonus', 'Бонусы')], default='card', max_length=20, verbose_name='Метод оплаты')),
                ('is_test', models.BooleanField(default=True, verbose_name='Тестовый платеж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='main.appointment')),
                ('certificate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transaction', to='main.certificate')),
            ],
            options={
                'verbose_name': 'Платежная транзакция',
                'verbose_name_plural': 'Платежные транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=120, verbose_name='Событие')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='Подпись валидна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Лог платежа',
                'verbose_name_plural': 'Логи платежей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Промокод')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Изображение')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия акции')),
                ('services', models.ManyToManyField(blank=True, related_name='promotions', to='main.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='promo_code_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.promotion', verbose_name='Примененная акция'),
        ),
    ]
