# Generated by Django 5.1.15 on 2026-04-23 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_loyaltysettings_appointment_bonus_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Заявка на авторство',
                'verbose_name_plural': 'Заявки на авторство',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'График мастера',
                'verbose_name_plural': 'Графики мастеров',
                'ordering': ['master', 'weekday'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AddField(
            model_name='master',
            name='can_publish_blog',
            field=models.BooleanField(default=False, verbose_name='Может публиковать статьи'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено администратором'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('master', 'date', 'time'), name='unique_master_time_slot'),
        ),
        migrations.AddField(
            model_name='authorrequest',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_requests', to='main.master'),
        ),
        migrations.AddField(
            model_name='masterschedule',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.master'),
        ),
        migrations.AlterUniqueTogether(
            name='masterschedule',
            unique_together={('master', 'weekday')},
        ),
    ]
