# Generated by Django 5.1.15 on 2026-04-23 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_authorrequest_masterschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Фон баннера')),
                ('certificate_background', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Фон сертификата')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='certificate_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='main.certificate', verbose_name='Примененный сертификат'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_option',
            field=models.CharField(choices=[('card', 'Предоплата картой'), ('bonus', 'Оплата бонусами'), ('certificate', 'Оплата сертификатом')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Действителен до'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Дата работы')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало перерыва')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец перерыва')),
                ('blocked_slots', models.JSONField(blank=True, default=list, verbose_name='Заблокированные слоты')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Выходной')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_schedules', to='main.master')),
            ],
            options={
                'verbose_name': 'Расписание мастера',
                'verbose_name_plural': 'Расписание мастеров',
                'ordering': ['work_date', 'start_time'],
                'unique_together': {('master', 'work_date')},
            },
        ),
    ]
