# Generated by Django 5.1.15 on 2026-05-11 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_masterjobapplication_portfolioimage_show_on_homepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.appointment', verbose_name='Запись'),
        ),
    ]
